version: "3"

services:
    web:
        container_name: x1-web
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
        volumes:
            - .:/app
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
    php-fpm:
        container_name: x1-fpm
        command: bash -c "/usr/bin/supervisord && php-fpm -F"
        build:
            context: .
            dockerfile: ./.docker/php-fpm/Dockerfile
        restart: always
        volumes:
            - .:/app
            - ./.docker/supervisor:/etc/supervisor/conf.d
    caddy:
        container_name: x1-caddy
        image: dunglas/mercure
        restart: always
        environment:
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
            MERCURE_SUBSCRIBER_JWT_KEY: "!ChangeThisMercureHubJWTSecretKey!"
        command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
        ports:
            - "8081:80"
        volumes:
            - ./.docker/caddy_data:/data
            - ./.docker/caddy_config:/config
    rabbitmq:
        container_name: x1-rabbitmq
        image: rabbitmq:3-management-alpine
        restart: always
        environment:
            RABBITMQ_ERLANG_COOKIE: "ZQLSSSKDQPYFHWEROOAH"
            RABBITMQ_DEFAULT_USER: "rabbitmq"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - 5672:5672
            - 15672:15672
    db:
        container_name: x1-db
        image: mariadb:latest
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_hungarian_ci
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        volumes:
            - ./.docker/db/:/docker-entrypoint-initdb.d
            - ./.docker/db:/var/lib/mysql
    phpmyadmin:
        container_name: x1-phpmyadmin
        image: phpmyadmin:latest
        restart: always
        ports:
            - "8080:80"
        depends_on:
            - db
        environment:
            - PMA_HOST=db
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=123456